version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www/html/
        ports:
            - "8080:80"
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
       image: mysql:5.7
       environment:
           - "MYSQL_DATABASE=homestead"
           - "MYSQL_USER=homestead"
           - "MYSQL_PASSWORD=secret"
           - "MYSQL_ROOT_PASSWORD=secret"
       ports:
           - "3307:3306"
